### ISSUE TITLE
Toevoegen API-58 No sensitive information in URIs 

### ISSUE THREAD

**Issue by logius-standaardenbeheer** [Logius-standaarden/Digikoppeling-Koppelvlakstandaard-REST-API#15]
# Aanleiding

Uit het Onderzoek ‘verwijzing naar de 'ADR API Security Extensie' vanuit de Digikoppeling Beveiligingsvoorschriften’

https://logius.nl/diensten/digikoppeling/documentatie/digikoppeling-roadmap-2022-2023#index-9

Is regel API-58 ‘No sensitive information in URIs’ gekomen als geschikt om normatief te maken.

# Wijziging

## API-58 No sensitive information in URIs

https://docs.geostandaarden.nl/api/API-Strategie-ext/#api-58 No sensitive information in URIs

_Do not put any sensitive information in URIs_
_Even when the connection is secure URIs can be cached and logged, in systems outside the control of client and/or server._

## Toelichting

Zelfs bij gebruik van op TLS gebaseerde beveiligde verbindingen is informatie in URI's niet beveiligd. URI's kunnen in de cache worden opgeslagen en worden gelogd buiten de servers die worden beheerd door clients en servers. Alle informatie daarin moet daarom als leesbaar worden beschouwd door iedereen met toegang tot het netwerk dat wordt gebruikt (in het geval van internet de hele wereld) en MAG GEEN gevoelige informatie bevatten. Noch clientgeheimen die worden gebruikt voor authenticatie, privacygevoelige informatie zoals BSN's of andere informatie die niet mag worden gedeeld. Houd er rekening mee dat zoekopdrachten (alles na de '?' in een URI) ook deel uitmaken van een URI.

## Voorgestelde aanpassing

Regel API-58 wordt toegevoegd aan:
https://publicatie.centrumvoorstandaarden.nl/dk/restapi/#afspraken-api-design-rules-extensies

Zie wijzigingen:
[Wijzigingen Pull request](https://github.com/Logius-standaarden/Digikoppeling-Koppelvlakstandaard-REST-API/pull/13/files)

Zie voorgestelde aanpassing:
[Aangepaste versie (preview)](https://github.com/Logius-standaarden/Digikoppeling-Koppelvlakstandaard-REST-API/blob/61927a5855e98f25280781b097c986a33ce7e403/ch03_Digikoppeling%20Restful%20API%20profiel.md#afspraken-api-design-rules-extensies)

# Bijlage Overzicht regels in ADR Security Extensie

|Regel uit ADR extensie | Overgenomen in huidige versie DK REST-API | Opmerking |
| --- | --- | --- |
|[API-11: Secure connections using TLS](https://docs.geostandaarden.nl/api/API-Strategie-ext/#api-11) | Nee | TLS Regel is vervangen door algemene regels vanuit DK Beveiligingsvoorschriften|
[API-58: No sensitive information in URIs](https://docs.geostandaarden.nl/api/API-Strategie-ext/#api-58) | Nee | Voorstel is deze regel wel op te nemen |
[API-13: Accept tokens as HTTP headers only](https://docs.geostandaarden.nl/api/API-Strategie-ext/#api-13) | Ja | |
[API-52: Use OAuth 2.0 for authorization with rights delegation](https://docs.geostandaarden.nl/api/API-Strategie-ext/#api-52)| Nee |  Buiten scope Digikoppeling|
[API-50: Use CORS to control access](https://docs.geostandaarden.nl/api/API-Strategie-ext/#api-50) | Nee|  Niet van toepassing op M2M verkeer |

**Comment by mrtn78** [comment]
Graag de verwijzing naar API Design rule API-58 uitbreiden met de voorgestelde oplossingsrichting die is beschreven in [Pull request 464](https://github.com/Geonovum/KP-APIs/pull/464)
> Do not put any sensitive information in URIs - Use the POST or QUERY HTTP operation instead.
