### ISSUE TITLE
Afkortingen reduceren [OPMERKING]

### ISSUE THREAD

**Issue by EdoPlantinga** [Logius-standaarden/Digikoppeling-Koppelvlakstandaard-REST-API#4]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

Suggestie: ik zie veel afkortingen in het document die wat overbodig zijn en het document onnodig lastig leesbaar maken voor nieuwkomers. PTLU wordt bijvoorbeeld maar 2 keer gebruikt: waarom het dan niet gewoon uitschrijven? Idem voor DK en PKIO, ik zou willen suggereren dit gewoon uit te schrijven.

**Comment by edwinwisse** [comment]
Respec heeft een mogelijkheid om een popup te tonen met een uitgeschreven afkorting. Gebruik van zo'n pop-up nemen we op in de schrijfwijzer voor onze documentatie.
