### ISSUE TITLE
Verplichte ondersteuning TLS 1.2

### ISSUE THREAD

**Issue by dmeijboom** [Logius-standaarden/Digikoppeling-Koppelvlakstandaard-REST-API#6]
In [Digikoppeling beveiligingsstandaarden en voorschriften](https://logius.nl/sites/default/files/bestanden/website/Digikoppeling_Beveiligingsstandaarden_en_voorschriften_v1.3.pdf) hoofdstuk 4.2 nummer `TLS004` is het voorschift als volgt.

> Een Serviceaanbieder is verplicht TLS versie 1.2 te ondersteunen, daarnaast is het aanbevolenvoor een Serviceaanbieder om TLS versie 1.3 te ondersteunen.
(...)

NCSC geeft aan dat de beste bescherming wordt geboden door TLS 1.3, dit onderschrijven wij ook. Daarnaast heeft deze versie inmiddels het [veiligheidsniveau "Voldoende"](https://www.ncsc.nl/documenten/publicaties/2021/januari/19/ict-beveiligingsrichtlijnen-voor-transport-layer-security-2.1) in plaats van "Goed".

Is het (zeker voor de toekomstbestendigheid) niet beter om hier expliciet voor TLS 1.3 te kiezen?

**Comment by mrtn78** [comment]
Mee eens

**Comment by Phering** [comment]
Dit is een onderwerp dat behandeld wordt in het `Digikoppeling Beveiligingsstandaarden en -voorschriften`. 

In het Technisch Overleg Digikoppeling van 4 maart wordt  een nieuwe update besproken [https://logius-standaarden.github.io/Digikoppeling-Beveiligingsstandaarden-en-voorschriften/](https://logius-standaarden.github.io/Digikoppeling-Beveiligingsstandaarden-en-voorschriften/), waaraan we voorstellen hoe we hier een mouw aan willen passen.

 Zie voor informatie over die wijziging de stukken van het TO : [https://github.com/Logius-standaarden/Digikoppeling-Technisch-Overleg/tree/main/2021/2021-maart-4](https://github.com/Logius-standaarden/Digikoppeling-Technisch-Overleg/tree/main/2021/2021-maart-4)
