### ISSUE TITLE
[OPMERKING] Ter informatie: het team van NLX.io ambieert om aan deze standaard voldoen

### ISSUE THREAD

**Issue by EdoPlantinga** [Logius-standaarden/Digikoppeling-Koppelvlakstandaard-REST-API#7]
Ter informatie: NLX is het integratiemechanisme van de [Common Ground](https://commonground.nl/) visie van de Nederlandse gemeenten. We kijken naar deze standaard met ons team en we willen graag dat NLX compatibel is met deze standaard. We staan er ook voor open om de referentieimplementatie te zijn voor deze standaard voor wat betreft het deel van mTLS, PKIoverheid en OIN. We gaan hier graag nader het gesprek over aan. 
[Meer informatie over NLX](https://nlx.io/).

**Comment by edwinwisse** [comment]
Hierover is contact geweest tussen VNG/NLX en Logius. VNG heeft een voorstel gedaan waarbij NLX principes als wijzigingsvoorstel op de Digikoppeling standaard worden ingediend. Logius staat als beheerorganisatie open voor deze (en andere) wijzigingsvoorstellen. Hiermee kan de gewenste compatibiliteit gerealiseerd worden. 
We sluiten hiermee dit issue.
